import time
import numpy as np

print(np.array([3.14, 4, 2, 3]))
print(np.array([1, 4, 2, 3], dtype='float32'))
a1 = np.array([3.14, 4, 2, 3])
print(type(a1))
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(type(a2))
print(a2.shape)
print(a2.ndim)
print(a2.dtype)
print(a2.size)

print(np.zeros((2, 4), dtype=int))
print(np.ones((3, 5)))
print(np.arange(0, 20, 2))
print(np.full((3, 5), 6.9))
print(np.linspace(0, 1, 5))

print(np.random.random((4, 4)))
np.random.seed(0)
print(np.random.random((4, 4)))
print(np.random.rand(4, 4))
print(np.random.normal(0, 1, (3, 3))) #1 là độ lệch so với 0
print(np.random.randint(0, 10, (4, 5)))

x1 = np.random.randint(20, size=6)
print(x1)
print(x1[4])
x2 = np.random.randint(10, size=(3, 4))
print(x2)
print(x2[1, 2])
x2[1, 2] = 9
print(x2)

print(x1)
print(x1[0:3])
print(x1[::2])
print(x2)
print(x2[:2, :3])
print(x2[:2,:])
print(x2[:,:1])

grid = np.arange(1, 10)
print(grid)
print(grid.shape)
grid.reshape((3,3))
print(grid.reshape((3,3)))
print(grid.reshape((3,3)).T)

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate((x,y))) #axis = 0 default
grid = np.array([[1, 2, 3], [4, 5, 6]])
print(np.concatenate((grid,grid), axis=0))
print(np.concatenate((grid,grid), axis=1))
print(np.vstack((x, grid)))
y = np.array([[11], [12]])
print(np.hstack((y, grid)))
print(np.split(x, [1,3]))
x1, x2, x3 = np.split(x, [1,3])
print(x1)
print(x2)
print(x3)

a = np.arange(3)
print(a)
print(a + 5)
b = np.ones((3, 3))
print(b)
print(a + b)
c = np.arange(3).reshape((3, 1))
print(c)
print(a + c)

print(a)
print(sum(a))
massive_array = np.random.random(1000)
# start_time = time.time()
print(sum(massive_array))
# end_time = time.time()
# print((end_time - start_time)*1000)
# start_time2 = time.time()
print(np.sum(massive_array))
# end_time2 = time.time()
# print((end_time2 - start_time2)*1000)
print(np.mean(massive_array))
print(np.max(massive_array))
print(np.min(massive_array))

dog_height = [600, 470, 170, 430, 300]
dog_height = np.array(dog_height)
print(np.std(dog_height))
print(np.var(dog_height))

x = np.array([2, 1, 4, 3, 5])
print(np.sort(x))
print(np.argsort(x))
np.random.seed(42)
MatA = np.random.randint(0, 10, size=(4, 6))
print(MatA)
print(np.sort(MatA, axis=0))
print(np.sort(MatA, axis=1))

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[6, 5], [4, 3], [2, 1]])
print(A.dot(B))
print((B.T).dot(A))